# Generated by cpp11: do not edit by hand

lstar_cpp_col_sum_by_group <- function(data, indptr, indices, nrows, ncols, group, ngroups, lognorm) {
  .Call(`_lstar_lstar_cpp_col_sum_by_group`, data, indptr, indices, nrows, ncols, group, ngroups, lognorm)
}

lstar_cpp_viewer_cell_order <- function(primary_code, emb, ncells, grid) {
  .Call(`_lstar_lstar_cpp_viewer_cell_order`, primary_code, emb, ncells, grid)
}

lstar_cpp_subsample_de_rank <- function(data, indptr, indices, nrows, ngenes, membership, lognorm) {
  .Call(`_lstar_lstar_cpp_subsample_de_rank`, data, indptr, indices, nrows, ngenes, membership, lognorm)
}

lstar_cpp_markers_one_vs_rest <- function(S, NE, nper, ngroups, ngenes, ncells) {
  .Call(`_lstar_lstar_cpp_markers_one_vs_rest`, S, NE, nper, ngroups, ngenes, ncells)
}

lstar_cpp_overdispersion <- function(mean, var, nobs) {
  .Call(`_lstar_lstar_cpp_overdispersion`, mean, var, nobs)
}

lstar_cpp_stream_col_stats <- function(path, field, block, n_threads, lognorm, depth, depthScale, population) {
  .Call(`_lstar_lstar_cpp_stream_col_stats`, path, field, block, n_threads, lognorm, depth, depthScale, population)
}

lstar_cpp_stream_col_sum_by_group <- function(path, field, group, ngroups, lognorm, depth, depthScale, block, n_threads) {
  .Call(`_lstar_lstar_cpp_stream_col_sum_by_group`, path, field, group, ngroups, lognorm, depth, depthScale, block, n_threads)
}

lstar_cpp_read_csc_block <- function(path, field, g_lo, g_hi) {
  .Call(`_lstar_lstar_cpp_read_csc_block`, path, field, g_lo, g_hi)
}

lstar_cpp_read_csc_cols <- function(path, field, cols) {
  .Call(`_lstar_lstar_cpp_read_csc_cols`, path, field, cols)
}

lstar_cpp_read <- function(path) {
  .Call(`_lstar_lstar_cpp_read`, path)
}

lstar_cpp_write <- function(ds, path, chunk_elems, compression, level, format, shard_elems) {
  invisible(.Call(`_lstar_lstar_cpp_write`, ds, path, chunk_elems, compression, level, format, shard_elems))
}
