# Generated by cpp11: do not edit by hand

lstar_cpp_read <- function(path) {
  .Call(`_lstar_lstar_cpp_read`, path)
}

lstar_cpp_write <- function(ds, path) {
  invisible(.Call(`_lstar_lstar_cpp_write`, ds, path))
}
