# Generated by cpp11: do not edit by hand

lstar_cpp_col_sum_by_group <- function(data, indptr, indices, nrows, ncols, group, ngroups, lognorm) {
  .Call(`_lstar_lstar_cpp_col_sum_by_group`, data, indptr, indices, nrows, ncols, group, ngroups, lognorm)
}

lstar_cpp_subsample_de_rank <- function(data, indptr, indices, nrows, ngenes, membership, lognorm) {
  .Call(`_lstar_lstar_cpp_subsample_de_rank`, data, indptr, indices, nrows, ngenes, membership, lognorm)
}

lstar_cpp_read <- function(path) {
  .Call(`_lstar_lstar_cpp_read`, path)
}

lstar_cpp_write <- function(ds, path) {
  invisible(.Call(`_lstar_lstar_cpp_write`, ds, path))
}
