// Verify the WASM kernels match a dense JS reference (the third row of the conformance matrix:
// the same libstar core under Emscripten must agree with the C++/Python results).
import createLstarKernels from "../dist/lstar_kernels.mjs";

function approx(a, b, rtol = 1e-9, atol = 1e-12) {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (Math.abs(a[i] - b[i]) > atol + rtol * Math.abs(b[i])) return false;
  }
  return true;
}

// Dense reference for zero-aware per-column mean/var of a CSC matrix.
function refColMeanVar(data, indices, indptr, nrows, ncols, lognorm) {
  const mean = new Float64Array(ncols), varr = new Float64Array(ncols), nnz = new Int32Array(ncols);
  for (let j = 0; j < ncols; j++) {
    const col = new Float64Array(nrows);
    for (let k = indptr[j]; k < indptr[j + 1]; k++) {
      col[indices[k]] = lognorm ? Math.log1p(data[k]) : data[k];
    }
    let s = 0; for (let i = 0; i < nrows; i++) s += col[i];
    const m = s / nrows;
    let ss = 0; for (let i = 0; i < nrows; i++) ss += (col[i] - m) * (col[i] - m);
    mean[j] = m; varr[j] = nrows > 1 ? ss / (nrows - 1) : 0;
    nnz[j] = indptr[j + 1] - indptr[j];
  }
  return { mean, var: varr, nnz };
}

// A deterministic xorshift so the test data is fixed.
function makeCSC(nrows, ncols, density) {
  let st = 88172645463325252n;
  const rnd = () => { st ^= st << 13n; st ^= st >> 7n; st ^= st << 17n;
    return Number((st >> 11n) & 0xfffffffffffffn) / 0xfffffffffffff; };
  const indptr = new Int32Array(ncols + 1);
  const ind = [], dat = [];
  for (let j = 0; j < ncols; j++) {
    for (let i = 0; i < nrows; i++) {
      if (rnd() < density) { ind.push(i); dat.push(rnd() * 10 + 0.5); }
    }
    indptr[j + 1] = ind.length;
  }
  return { data: new Float64Array(dat), indices: new Int32Array(ind), indptr, nrows, ncols };
}

// Dense reference for per-group sufficient stats over a CSC (indices are row=cell ids).
function refColSumByGroup(data, indices, indptr, nrows, ncols, group, ngroups, lognorm) {
  const sum = new Float64Array(ngroups * ncols), sumsq = new Float64Array(ngroups * ncols), ne = new Float64Array(ngroups * ncols);
  for (let j = 0; j < ncols; j++) for (let k = indptr[j]; k < indptr[j + 1]; k++) {
    const g = group[indices[k]]; if (g < 0 || g >= ngroups) continue;
    let v = data[k]; if (lognorm) v = Math.log1p(v);
    const idx = g * ncols + j; sum[idx] += v; sumsq[idx] += v * v; ne[idx] += 1;
  }
  return { sum, sumsq, n_expr: ne };
}

// Dense reference for the subsample DE ranker over a CSR (indices are gene ids; indptr over rows).
function refSubsampleDeRank(data, indptr, indices, nrows, ngenes, membership, lognorm) {
  const sumA = new Float64Array(ngenes), sumB = new Float64Array(ngenes); let nA = 0, nB = 0;
  for (let r = 0; r < nrows; r++) { const m = membership[r]; if (m < 0) continue; if (m === 0) nA++; else nB++;
    for (let k = indptr[r]; k < indptr[r + 1]; k++) { const g = indices[k]; let v = data[k]; if (lognorm) v = Math.log1p(v); (m === 0 ? sumA : sumB)[g] += v; } }
  const meanA = new Float64Array(ngenes), meanB = new Float64Array(ngenes), lfc = new Float64Array(ngenes);
  for (let g = 0; g < ngenes; g++) { const ma = sumA[g] / Math.max(nA, 1), mb = sumB[g] / Math.max(nB, 1); meanA[g] = ma; meanB[g] = mb; lfc[g] = ma - mb; }
  return { meanA, meanB, lfc, nA, nB };
}

const M = await createLstarKernels();
console.log("  module:", M.version());

const { data, indices, indptr, nrows, ncols } = makeCSC(200, 80, 0.1);
let failures = 0;

for (const lognorm of [false, true]) {
  const got = M.colMeanVar(data, indptr, nrows, 1, lognorm);
  const ref = refColMeanVar(data, indices, indptr, nrows, ncols, lognorm);
  const ok = approx(got.mean, ref.mean, 1e-9) && approx(got.var, ref.var, 1e-7) &&
             approx(got.nnz, ref.nnz);
  console.log(`  colMeanVar lognorm=${lognorm}: ${ok ? "OK" : "MISMATCH"}`);
  if (!ok) failures++;
}

// csc_to_csr: nnz + total preserved, indptr monotone to nnz, indices in range.
{
  const r = M.cscToCsr(data, indices, indptr, nrows, ncols);
  let s1 = 0; for (const x of data) s1 += x;
  let s2 = 0; for (const x of r.data) s2 += x;
  const okNnz = r.data.length === data.length;
  const okSum = Math.abs(s1 - s2) <= 1e-9 * Math.abs(s1);
  const okPtr = r.indptr[0] === 0 && r.indptr[r.indptr.length - 1] === data.length;
  let mono = true; for (let i = 1; i < r.indptr.length; i++) if (r.indptr[i] < r.indptr[i - 1]) mono = false;
  let inRange = true; for (const c of r.indices) if (c < 0 || c >= ncols) inRange = false;
  const ok = okNnz && okSum && okPtr && mono && inRange;
  console.log(`  cscToCsr: ${ok ? "OK" : "MISMATCH"} (nnz=${r.data.length}, indptr[${r.indptr.length}]->${r.indptr[r.indptr.length - 1]})`);
  if (!ok) failures++;
}

// Cross-language conformance: the WASM kernel must match the Python kernel on the same input
// (fixture generated by lstar.stream_col_stats). This is the third binding agreeing with the others.
{
  const fs = await import("node:fs");
  const url = new URL("./fixture_python.json", import.meta.url);
  const fx = JSON.parse(fs.readFileSync(url, "utf8"));
  const data = new Float64Array(fx.data);
  const indptr = new Int32Array(fx.indptr);
  for (const lognorm of [false, true]) {
    const py = fx[`lognorm_${lognorm ? 1 : 0}`];
    const got = M.colMeanVar(data, indptr, fx.nrows, 1, lognorm);
    const ok = approx(got.mean, py.mean, 1e-9) && approx(got.var, py.var, 1e-7) &&
               approx(got.nnz, py.nnz);
    console.log(`  WASM vs Python lognorm=${lognorm}: ${ok ? "OK" : "MISMATCH"}`);
    if (!ok) failures++;
  }
}

// csc_col_sum_by_group: per-(group,gene) sum/sumsq/n_expr vs dense reference.
{
  const ngroups = 4; const group = new Int32Array(nrows); for (let i = 0; i < nrows; i++) group[i] = i % ngroups;
  for (const lognorm of [false, true]) {
    const got = M.colSumByGroup(data, indptr, indices, nrows, ncols, group, ngroups, lognorm);
    const ref = refColSumByGroup(data, indices, indptr, nrows, ncols, group, ngroups, lognorm);
    const ok = approx(got.sum, ref.sum, 1e-9) && approx(got.sumsq, ref.sumsq, 1e-7) && approx(got.n_expr, ref.n_expr) && got.ngenes === ncols;
    console.log(`  colSumByGroup lognorm=${lognorm}: ${ok ? "OK" : "MISMATCH"}`);
    if (!ok) failures++;
  }
}

// subsample_de_rank: log1p group means + lfc vs dense reference (CSR via cscToCsr).
{
  const csr = M.cscToCsr(data, indices, indptr, nrows, ncols);   // rows=cells, cols=genes
  const membership = new Int32Array(nrows); for (let i = 0; i < nrows; i++) membership[i] = i < nrows / 2 ? 0 : 1;
  const got = M.subsampleDeRank(csr.data, csr.indptr, csr.indices, nrows, ncols, membership, true);
  const ref = refSubsampleDeRank(csr.data, csr.indptr, csr.indices, nrows, ncols, membership, true);
  const ok = approx(got.meanA, ref.meanA, 1e-9) && approx(got.meanB, ref.meanB, 1e-9) && approx(got.lfc, ref.lfc, 1e-9) && got.nA === ref.nA && got.nB === ref.nB;
  console.log(`  subsampleDeRank: ${ok ? "OK" : "MISMATCH"} (nA=${got.nA}, nB=${got.nB})`);
  if (!ok) failures++;
}

console.log(failures === 0 ? "\nWASM kernels OK: match dense reference + the Python kernel" : `\nFAIL: ${failures}`);
process.exit(failures === 0 ? 0 : 1);
