// Verify the WASM kernels match a dense JS reference (the third row of the conformance matrix:
// the same libstar core under Emscripten must agree with the C++/Python results).
import createLstarKernels from "../dist/lstar_kernels.mjs";

function approx(a, b, rtol = 1e-9, atol = 1e-12) {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (Math.abs(a[i] - b[i]) > atol + rtol * Math.abs(b[i])) return false;
  }
  return true;
}

// Dense reference for zero-aware per-column mean/var of a CSC matrix.
function refColMeanVar(data, indices, indptr, nrows, ncols, lognorm) {
  const mean = new Float64Array(ncols), varr = new Float64Array(ncols), nnz = new Int32Array(ncols);
  for (let j = 0; j < ncols; j++) {
    const col = new Float64Array(nrows);
    for (let k = indptr[j]; k < indptr[j + 1]; k++) {
      col[indices[k]] = lognorm ? Math.log1p(data[k]) : data[k];
    }
    let s = 0; for (let i = 0; i < nrows; i++) s += col[i];
    const m = s / nrows;
    let ss = 0; for (let i = 0; i < nrows; i++) ss += (col[i] - m) * (col[i] - m);
    mean[j] = m; varr[j] = nrows > 1 ? ss / (nrows - 1) : 0;
    nnz[j] = indptr[j + 1] - indptr[j];
  }
  return { mean, var: varr, nnz };
}

// A deterministic xorshift so the test data is fixed.
function makeCSC(nrows, ncols, density) {
  let st = 88172645463325252n;
  const rnd = () => { st ^= st << 13n; st ^= st >> 7n; st ^= st << 17n;
    return Number((st >> 11n) & 0xfffffffffffffn) / 0xfffffffffffff; };
  const indptr = new Int32Array(ncols + 1);
  const ind = [], dat = [];
  for (let j = 0; j < ncols; j++) {
    for (let i = 0; i < nrows; i++) {
      if (rnd() < density) { ind.push(i); dat.push(rnd() * 10 + 0.5); }
    }
    indptr[j + 1] = ind.length;
  }
  return { data: new Float64Array(dat), indices: new Int32Array(ind), indptr, nrows, ncols };
}

const M = await createLstarKernels();
console.log("  module:", M.version());

const { data, indices, indptr, nrows, ncols } = makeCSC(200, 80, 0.1);
let failures = 0;

for (const lognorm of [false, true]) {
  const got = M.colMeanVar(data, indptr, nrows, 1, lognorm);
  const ref = refColMeanVar(data, indices, indptr, nrows, ncols, lognorm);
  const ok = approx(got.mean, ref.mean, 1e-9) && approx(got.var, ref.var, 1e-7) &&
             approx(got.nnz, ref.nnz);
  console.log(`  colMeanVar lognorm=${lognorm}: ${ok ? "OK" : "MISMATCH"}`);
  if (!ok) failures++;
}

// csc_to_csr: nnz + total preserved, indptr monotone to nnz, indices in range.
{
  const r = M.cscToCsr(data, indices, indptr, nrows, ncols);
  let s1 = 0; for (const x of data) s1 += x;
  let s2 = 0; for (const x of r.data) s2 += x;
  const okNnz = r.data.length === data.length;
  const okSum = Math.abs(s1 - s2) <= 1e-9 * Math.abs(s1);
  const okPtr = r.indptr[0] === 0 && r.indptr[r.indptr.length - 1] === data.length;
  let mono = true; for (let i = 1; i < r.indptr.length; i++) if (r.indptr[i] < r.indptr[i - 1]) mono = false;
  let inRange = true; for (const c of r.indices) if (c < 0 || c >= ncols) inRange = false;
  const ok = okNnz && okSum && okPtr && mono && inRange;
  console.log(`  cscToCsr: ${ok ? "OK" : "MISMATCH"} (nnz=${r.data.length}, indptr[${r.indptr.length}]->${r.indptr[r.indptr.length - 1]})`);
  if (!ok) failures++;
}

// Cross-language conformance: the WASM kernel must match the Python kernel on the same input
// (fixture generated by lstar.stream_col_stats). This is the third binding agreeing with the others.
{
  const fs = await import("node:fs");
  const url = new URL("./fixture_python.json", import.meta.url);
  const fx = JSON.parse(fs.readFileSync(url, "utf8"));
  const data = new Float64Array(fx.data);
  const indptr = new Int32Array(fx.indptr);
  for (const lognorm of [false, true]) {
    const py = fx[`lognorm_${lognorm ? 1 : 0}`];
    const got = M.colMeanVar(data, indptr, fx.nrows, 1, lognorm);
    const ok = approx(got.mean, py.mean, 1e-9) && approx(got.var, py.var, 1e-7) &&
               approx(got.nnz, py.nnz);
    console.log(`  WASM vs Python lognorm=${lognorm}: ${ok ? "OK" : "MISMATCH"}`);
    if (!ok) failures++;
  }
}

console.log(failures === 0 ? "\nWASM kernels OK: match dense reference + the Python kernel" : `\nFAIL: ${failures}`);
process.exit(failures === 0 ? 0 : 1);
