// Phase B: the zarrita-based L* reader must expose the manifest and read fields lazily, matching the
// values the Python writer produced (test/data generated by make_store.py).
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import { openLstar } from "../core/reader.ts";
import { NodeFSStore } from "../core/node-store.ts";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const expected = JSON.parse(fs.readFileSync(path.join(HERE, "data", "expected.json"), "utf8"));

function approx(a: ArrayLike<number>, b: ArrayLike<number>, rtol = 1e-5, atol = 1e-6): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (Math.abs(Number(a[i]) - Number(b[i])) > atol + rtol * Math.abs(Number(b[i]))) return false;
  }
  return true;
}
function eq(a: any[], b: any[]): boolean {
  return a.length === b.length && a.every((x, i) => x === b[i]);
}

let fail = 0;
const check = (name: string, ok: boolean) => { console.log(`  ${ok ? "OK" : "FAIL"}  ${name}`); if (!ok) fail++; };

const ds = await openLstar(new NodeFSStore(path.join(HERE, "data", "sample.lstar.zarr")));

check("manifest kind", ds.kind === expected.kind);
check("manifest axes", eq(ds.axisNames(), expected.axes));
check("manifest fields", eq(ds.fieldNames(), expected.fields));
check("axis lengths", ds.axes.get("cells")!.length === expected.n_cells &&
                      ds.axes.get("genes")!.length === expected.n_genes);
check("field meta (counts is csc measure)",
      ds.fields.get("counts")!.encoding === "csc" && ds.fields.get("counts")!.role === "measure" &&
      eq(ds.fields.get("counts")!.span, ["cells", "genes"]));

const genes = await ds.axisLabels("genes");
check("axisLabels(genes)", eq(genes, Array.from({ length: expected.n_genes }, (_, i) => "g" + i)));

const umap = await ds.fieldDense("umap");
check("fieldDense(umap) shape", umap.shape[0] === expected.n_cells && umap.shape[1] === 2);
check("fieldDense(umap) values", approx(umap.data, expected.umap));

const leiden = await ds.fieldStrings("leiden");
check("fieldStrings(leiden)", eq(leiden, expected.leiden));

// nullable: the validity mask (1 == missing) is exposed; a non-nullable field has none
const qcMask = await ds.fieldMask("qc");
check("fieldMeta(qc) nullable", ds.fields.get("qc")!.nullable === true);
check("fieldMask(qc)", qcMask !== null && eq(Array.from(qcMask!), expected.qc.mask));
check("fieldMask(n_umi) absent", (await ds.fieldMask("n_umi")) === null);

// the hot path: one CSC gene-column, fetched as a slice
const gc = expected.gene_col;
const { rows, vals } = await ds.cscColumn("counts", gc.index);
check("cscColumn rows", eq(Array.from(rows as any).map(Number), gc.rows));
check("cscColumn vals", approx(vals, gc.vals));

console.log(fail === 0 ? "\nreader OK" : `\nreader FAIL: ${fail}`);
process.exit(fail === 0 ? 0 : 1);
