#!/usr/bin/env bash
# Seurat version/class variety: "a Seurat object" is several structurally-different classes. These
# small fixtures are constructed by Seurat's own constructors (real classes, deterministic) -- grounded
# in an analysis of real objects -- and each must round-trip through the profile + produce a store that
# validates. Covers: v3/v4 `Assay`, v5 `Assay5`, a v5 *split* (integration) object (reads as a
# collection, re-splits on write-back), an `SCTAssay`, and a multimodal RNA+ADT object (the second
# assay is a Tier-3 gap -> must be *recorded* as dropped, never silently lost).
set -eo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RLIB="$ROOT/.Rlib"

# Synthetic CITE-seq (cells x features Matrix-Market), generated by the shared Python generator so the
# Seurat multimodal fixture uses the *same* synthetic RNA+ADT as the MuData/SCE tests. Nothing committed.
CDIR="$ROOT/testdata/citeseq"
python3 "$ROOT/python/tests/synth.py" citeseq "$CDIR" >/dev/null

# Use the lightweight SeuratObject (classes/constructors), NOT the full `Seurat` umbrella -- Seurat pulls
# heavy runtime deps that install-but-fail-to-load on a minimal CI runner (the prior r-cross-format
# failure: it died in ~3s on `library(Seurat)`). Everything here (Assay/Assay5, split layers, DimReduc,
# Idents, CreateAssay5Object) lives in SeuratObject; only SCTransform needs full Seurat -> guarded below.
# This R program is large, so pass it as a FILE, NOT via `Rscript -e`: a big `-e` expression overflows
# R's command-line buffer (~8KB once R re-encodes every space/newline to ~+~/~n~), after which R prints a
# `WARNING: '-e ...'` and silently runs NOTHING (exit 0, no output) -- which then trips `set -o pipefail`
# at the grep below for a confusing failure. A *quoted* heredoc keeps every `$` in the R code literal;
# $RLIB/$CDIR arrive via commandArgs; </dev/null keeps R from blocking on the harness socket stdin.
RSRC="$(mktemp --suffix=.R)"; trap 'rm -f "$RSRC"' EXIT
cat > "$RSRC" <<'RSCRIPT'
args <- commandArgs(trailingOnly = TRUE); RLIB <- args[1]; cdir <- args[2]
.libPaths(c(RLIB, .libPaths())); suppressMessages({library(SeuratObject); library(lstar)})
set.seed(1); ng <- 120; nc <- 60
m <- matrix(rpois(ng*nc, 3), ng, nc, dimnames = list(paste0("Gene",1:ng), paste0("Cell",1:nc)))
emb <- matrix(rnorm(nc*5), nc, 5, dimnames = list(colnames(m), paste0("PC_",1:5)))
withpca <- function(so) { so[["pca"]] <- CreateDimReducObject(emb, key="PC_", assay=DefaultAssay(so), stdev=sqrt(5:1)); Idents(so) <- factor(rep(c("A","B"), length.out=nc)); so }

rt <- function(tag, so, checks) {
  ds <- read_seurat(so); so2 <- write_seurat(ds); stopifnot(checks(ds, so2)); cat(sprintf("  [R] %-22s OK\n", tag))
  p <- file.path("/tmp", paste0("sv_", gsub("[^a-z0-9]","", tolower(tag)), ".lstar.zarr"))
  if (dir.exists(p)) unlink(p, recursive=TRUE); lstar_write(ds, p); p
}
stores <- c()

options(Seurat.object.assay.version = "v3")
stores <- c(stores, rt("v3 Assay", withpca(CreateSeuratObject(m)), function(ds, so2)
  inherits(so2[["RNA"]], "Assay") && identical(ds$kind, "sample") && "pca" %in% Reductions(so2) &&
  any(grepl("assay@RNA:Assay$", ds$profiles))))         # version tracked: v3 Assay class recorded
options(Seurat.object.assay.version = "v5")
stores <- c(stores, rt("v5 Assay5", withpca(CreateSeuratObject(m)), function(ds, so2)
  inherits(so2[["RNA"]], "Assay5") && "pca" %in% Reductions(so2) &&
  any(grepl("assay@RNA:Assay5", ds$profiles))))         # version tracked: v5 Assay5 class recorded

# HVG-subset loadings: real PCA loadings cover only the variable features (e.g. pbmc3k.final 2000/13714).
# A reduction whose feature.loadings span a gene SUBSET must be captured over a `<reduction>_features`
# subset axis (not dropped) and restored on write-back -- exercise that here with loadings over 60/120 genes.
Lsub <- matrix(rnorm(60*5), 60, 5, dimnames = list(paste0("Gene", 1:60), paste0("PC_", 1:5)))
sosub <- CreateSeuratObject(m)
sosub[["pca"]] <- CreateDimReducObject(emb, loadings = Lsub, key = "PC_", assay = "RNA")
stores <- c(stores, rt("HVG-subset loadings", sosub, function(ds, so2)
  identical(as.character(ds$fields[["pca_loadings"]]$span), c("pca_features", "pca")) &&
  length(ds$axes[["pca_features"]]$labels) == 60 && length(ds$dropped) == 0 &&
  nrow(Loadings(so2[["pca"]])) == 60 &&
  isTRUE(all.equal(unname(Loadings(so2[["pca"]])), unname(Lsub), check.attributes = FALSE))))

# scale.data over a GENE SUBSET (default ScaleData scales only variable features) -> a partial-coverage
# measure over (cells, genes) keyed by an index into the gene axis; restored over its covered genes.
sosd <- CreateSeuratObject(m)
sdsub <- matrix(rnorm(60*nc), 60, nc, dimnames = list(paste0("Gene", 1:60), colnames(m)))
LayerData(sosd[["RNA"]], "scale.data") <- sdsub
stores <- c(stores, rt("scale.data subset (partial)", sosd, function(ds, so2)
  identical(ds$fields[["scale.data"]]$coverage, "partial") &&
  length(ds$fields[["scale.data"]]$index) == 60 && length(ds$dropped) == 0 &&
  isTRUE(all.equal(unname(LayerData(so2[["RNA"]], "scale.data")), unname(sdsub), check.attributes = FALSE))))

# Neighbor (FindNeighbors(return.neighbor=TRUE)): nn.idx/nn.dist -> a weighted cell-cell relation
knn <- 5; nnidx <- t(sapply(1:nc, function(i) sample(setdiff(1:nc, i), knn)))
nnobj <- methods::new("Neighbor", nn.idx = nnidx, nn.dist = matrix(runif(nc*knn), nc, knn),
                      cell.names = colnames(m), alg.info = list())
sonn <- CreateSeuratObject(m); sonn[["pca.nn"]] <- nnobj
stores <- c(stores, rt("Neighbor (nn graph)", sonn, function(ds, so2)
  identical(ds$fields[["nn_pca.nn"]]$role, "relation") &&
  identical(as.character(ds$fields[["nn_pca.nn"]]$span), c("cells", "cells")) &&
  length(ds$fields[["nn_pca.nn"]]$values@x) == nc*knn))

so5 <- CreateSeuratObject(m); so5$samp <- rep(c("s1","s2"), each = nc/2)
so5[["RNA"]] <- split(so5[["RNA"]], f = so5$samp)
stores <- c(stores, rt("v5 split (collection)", so5, function(ds, so2)
  identical(ds$kind, "collection") && setequal(Layers(so2[["RNA"]]), c("counts.s1","counts.s2"))))

sct <- tryCatch({                                       # SCTransform needs full Seurat -> skip if absent
  if (!requireNamespace("Seurat", quietly = TRUE)) NULL
  else suppressWarnings(suppressMessages(Seurat::SCTransform(CreateSeuratObject(m), verbose = FALSE)))
}, error = function(e) NULL)
if (!is.null(sct)) stores <- c(stores, rt("SCTAssay", sct, function(ds, so2) length(ds$fields) >= 3)) else
  cat("  [R] SCTAssay               SKIP (SCTransform unavailable)\n")

# multimodal: synthetic CITE-seq (the same generated fixture the MuData/SCE tests use). The *real* RNA+ADT
# breadth lives in the local corpus (real_corpus_r.sh / sweep). Matrix-Market is cells x features -> t().
# cdir was set from commandArgs() at the top of this script
crna <- Matrix::t(Matrix::readMM(file.path(cdir, "rna.mtx"))); cadt <- Matrix::t(Matrix::readMM(file.path(cdir, "adt.mtx")))
ccells <- readLines(file.path(cdir, "cells.txt"))
dimnames(crna) <- list(readLines(file.path(cdir, "genes.txt")), ccells)
dimnames(cadt) <- list(readLines(file.path(cdir, "proteins.txt")), ccells)
mm <- CreateSeuratObject(as(crna, "CsparseMatrix")); mm[["ADT"]] <- CreateAssay5Object(counts = as(cadt, "CsparseMatrix"))
stores <- c(stores, rt("multimodal RNA+ADT (synth)", mm, function(ds, so2)  # ADT captured as 2nd feature space
  "ADT" %in% names(ds$axes) && identical(ds$axes$ADT$role, "feature") &&
  identical(as.character(ds$fields[["ADT.counts"]]$span), c("cells","ADT")) &&
  setequal(Assays(so2), c("RNA","ADT")) && nrow(so2[["ADT"]]) == 29 &&
  isTRUE(all.equal(as.matrix(LayerData(so2[["ADT"]],"counts")), as.matrix(cadt), check.attributes = FALSE))))

# 4-assay ECCITE-style object (RNA + ADT + HTO + GDO): N feature spaces over one cells axis -- guards the
# multimodal path for >2 assays (real thp1.eccite has these 4). No Signac needed.
mkA <- function(nf) { x <- matrix(rpois(nf*nc, 2), nf, nc); dimnames(x) <- list(paste0("F", 1:nf), colnames(m)); as(x, "CsparseMatrix") }
ecc <- CreateSeuratObject(m)
ecc[["ADT"]] <- CreateAssay5Object(counts = mkA(8)); ecc[["HTO"]] <- CreateAssay5Object(counts = mkA(4))
ecc[["GDO"]] <- CreateAssay5Object(counts = mkA(6))
stores <- c(stores, rt("4-assay ECCITE (RNA+ADT+HTO+GDO)", ecc, function(ds, so2)
  all(c("ADT","HTO","GDO") %in% names(ds$axes)) &&
  all(vapply(c("ADT","HTO","GDO"), function(a) identical(ds$axes[[a]]$role, "feature"), logical(1))) &&
  setequal(Assays(so2), c("RNA","ADT","HTO","GDO"))))

# synthetic Signac ChromatinAssay: peaks + genomic ranges -> a peak feature axis + typed ranges
# (<axis>_seqnames/_start/_end). Guards the real-pbmcMultiome capture. Skips where Signac is absent.
if (requireNamespace("Signac", quietly = TRUE)) {
  npk <- 20; pk <- sprintf("chr%d-%d-%d", rep(1:2, length.out = npk), seq(1, by = 1000, length.out = npk), seq(500, by = 1000, length.out = npk))
  pm <- matrix(rpois(npk*nc, 1), npk, nc); dimnames(pm) <- list(pk, colnames(m))
  ca <- Signac::CreateChromatinAssay(counts = as(pm, "CsparseMatrix"), ranges = Signac::StringToGRanges(pk, sep = c("-", "-")))
  cao <- CreateSeuratObject(m); cao[["ATAC"]] <- ca
  stores <- c(stores, rt("ChromatinAssay (synthetic)", cao, function(ds, so2)
    "ATAC" %in% names(ds$axes) && identical(ds$axes$ATAC$role, "feature") &&
    "ATAC_seqnames" %in% names(ds$fields) && identical(ds$fields[["ATAC_start"]]$role, "measure")))
} else cat("  [R] ChromatinAssay (synthetic)   SKIP (Signac unavailable)\n")

# spatial coordinates (Visium/FOV) live in so@images, NOT Reductions -> captured as a `spatial` observed
# coordinate axis (mirrors the AnnData spatial-obsm path); the pixel images are recorded (deferred tier).
# This was a silent loss (real stxBrain/Visium). CreateFOV is in SeuratObject -> runs in CI, no Signac.
spc <- data.frame(x = runif(nc), y = runif(nc), row.names = colnames(m))
sosp <- CreateSeuratObject(m); sosp[["fov"]] <- SeuratObject::CreateFOV(spc, type = "centroids", assay = "RNA")
stores <- c(stores, rt("spatial coords (FOV)", sosp, function(ds, so2)
  identical(ds$axes$spatial$role, "coordinate") && identical(ds$axes$spatial$origin, "observed") &&
  identical(ds$fields[["spatial"]]$subtype, "spatial") && any(grepl("image/fov/pixels", ds$dropped))))
cat(paste(stores, collapse="\n"), "\n", file = "/tmp/sv_stores.txt")
RSCRIPT
Rscript "$RSRC" "$RLIB" "$CDIR" </dev/null 2>&1 | grep -E "^  \[R\]|Error|Execution halted|cannot|unable|no method"

# every version fixture produced a store that validates in Python (cross-language)
PYTHONPATH="$ROOT/python/src" python3 - <<'PY'
import warnings; warnings.filterwarnings("ignore")
import os, tempfile, lstar
stores = [s for s in open("/tmp/sv_stores.txt").read().split() if s]
for p in stores:
    errs = [i for i in lstar.validate(lstar.read(p)) if i.startswith("ERROR")]
    assert not errs, (p, errs)
print("  [py] all %d Seurat version-variant stores validate clean" % len(stores))
PY
