// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// lstar_cpp.cpp
list lstar_cpp_col_sum_by_group(doubles data, integers indptr, integers indices, int nrows, int ncols, integers group, int ngroups, bool lognorm);
extern "C" SEXP _lstar_lstar_cpp_col_sum_by_group(SEXP data, SEXP indptr, SEXP indices, SEXP nrows, SEXP ncols, SEXP group, SEXP ngroups, SEXP lognorm) {
  BEGIN_CPP11
    return cpp11::as_sexp(lstar_cpp_col_sum_by_group(cpp11::as_cpp<cpp11::decay_t<doubles>>(data), cpp11::as_cpp<cpp11::decay_t<integers>>(indptr), cpp11::as_cpp<cpp11::decay_t<integers>>(indices), cpp11::as_cpp<cpp11::decay_t<int>>(nrows), cpp11::as_cpp<cpp11::decay_t<int>>(ncols), cpp11::as_cpp<cpp11::decay_t<integers>>(group), cpp11::as_cpp<cpp11::decay_t<int>>(ngroups), cpp11::as_cpp<cpp11::decay_t<bool>>(lognorm)));
  END_CPP11
}
// lstar_cpp.cpp
list lstar_cpp_subsample_de_rank(doubles data, integers indptr, integers indices, int nrows, int ngenes, integers membership, bool lognorm);
extern "C" SEXP _lstar_lstar_cpp_subsample_de_rank(SEXP data, SEXP indptr, SEXP indices, SEXP nrows, SEXP ngenes, SEXP membership, SEXP lognorm) {
  BEGIN_CPP11
    return cpp11::as_sexp(lstar_cpp_subsample_de_rank(cpp11::as_cpp<cpp11::decay_t<doubles>>(data), cpp11::as_cpp<cpp11::decay_t<integers>>(indptr), cpp11::as_cpp<cpp11::decay_t<integers>>(indices), cpp11::as_cpp<cpp11::decay_t<int>>(nrows), cpp11::as_cpp<cpp11::decay_t<int>>(ngenes), cpp11::as_cpp<cpp11::decay_t<integers>>(membership), cpp11::as_cpp<cpp11::decay_t<bool>>(lognorm)));
  END_CPP11
}
// lstar_cpp.cpp
list lstar_cpp_stream_col_stats(std::string path, std::string field, int block, int n_threads, bool lognorm);
extern "C" SEXP _lstar_lstar_cpp_stream_col_stats(SEXP path, SEXP field, SEXP block, SEXP n_threads, SEXP lognorm) {
  BEGIN_CPP11
    return cpp11::as_sexp(lstar_cpp_stream_col_stats(cpp11::as_cpp<cpp11::decay_t<std::string>>(path), cpp11::as_cpp<cpp11::decay_t<std::string>>(field), cpp11::as_cpp<cpp11::decay_t<int>>(block), cpp11::as_cpp<cpp11::decay_t<int>>(n_threads), cpp11::as_cpp<cpp11::decay_t<bool>>(lognorm)));
  END_CPP11
}
// lstar_cpp.cpp
list lstar_cpp_read_csc_block(std::string path, std::string field, int g_lo, int g_hi);
extern "C" SEXP _lstar_lstar_cpp_read_csc_block(SEXP path, SEXP field, SEXP g_lo, SEXP g_hi) {
  BEGIN_CPP11
    return cpp11::as_sexp(lstar_cpp_read_csc_block(cpp11::as_cpp<cpp11::decay_t<std::string>>(path), cpp11::as_cpp<cpp11::decay_t<std::string>>(field), cpp11::as_cpp<cpp11::decay_t<int>>(g_lo), cpp11::as_cpp<cpp11::decay_t<int>>(g_hi)));
  END_CPP11
}
// lstar_cpp.cpp
list lstar_cpp_read(std::string path);
extern "C" SEXP _lstar_lstar_cpp_read(SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(lstar_cpp_read(cpp11::as_cpp<cpp11::decay_t<std::string>>(path)));
  END_CPP11
}
// lstar_cpp.cpp
void lstar_cpp_write(list ds, std::string path);
extern "C" SEXP _lstar_lstar_cpp_write(SEXP ds, SEXP path) {
  BEGIN_CPP11
    lstar_cpp_write(cpp11::as_cpp<cpp11::decay_t<list>>(ds), cpp11::as_cpp<cpp11::decay_t<std::string>>(path));
    return R_NilValue;
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_lstar_lstar_cpp_col_sum_by_group",  (DL_FUNC) &_lstar_lstar_cpp_col_sum_by_group,  8},
    {"_lstar_lstar_cpp_read",              (DL_FUNC) &_lstar_lstar_cpp_read,              1},
    {"_lstar_lstar_cpp_read_csc_block",    (DL_FUNC) &_lstar_lstar_cpp_read_csc_block,    4},
    {"_lstar_lstar_cpp_stream_col_stats",  (DL_FUNC) &_lstar_lstar_cpp_stream_col_stats,  5},
    {"_lstar_lstar_cpp_subsample_de_rank", (DL_FUNC) &_lstar_lstar_cpp_subsample_de_rank, 7},
    {"_lstar_lstar_cpp_write",             (DL_FUNC) &_lstar_lstar_cpp_write,             2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_lstar(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
