// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// lstar_cpp.cpp
list lstar_cpp_read(std::string path);
extern "C" SEXP _lstar_lstar_cpp_read(SEXP path) {
  BEGIN_CPP11
    return cpp11::as_sexp(lstar_cpp_read(cpp11::as_cpp<cpp11::decay_t<std::string>>(path)));
  END_CPP11
}
// lstar_cpp.cpp
void lstar_cpp_write(list ds, std::string path);
extern "C" SEXP _lstar_lstar_cpp_write(SEXP ds, SEXP path) {
  BEGIN_CPP11
    lstar_cpp_write(cpp11::as_cpp<cpp11::decay_t<list>>(ds), cpp11::as_cpp<cpp11::decay_t<std::string>>(path));
    return R_NilValue;
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_lstar_lstar_cpp_read",  (DL_FUNC) &_lstar_lstar_cpp_read,  1},
    {"_lstar_lstar_cpp_write", (DL_FUNC) &_lstar_lstar_cpp_write, 2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_lstar(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
